name: Build Plugins

on:
  push:
    branches:
      - main
    paths:
      - "plugins/**"
      - ".github/workflows/build-plugins.yml"

jobs:
  build:
    name: Build updated plugins
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        fetch-depth: 0
        submodules: "recursive"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@fb1fe28aa9ff24afc553b37545437005a4cf2115
      with:
        sha: ${{ github.sha }}
        files: |
          plugins/*

    - name: Cache Docker images
      uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052

    - name: Login to GitHub Container Registry
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u SteamDeckHomebrew --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull builder image
      run: docker pull ghcr.io/steamdeckhomebrew/builder:latest

    - name: Log out of GitHub Container Registry
      run: |
        docker logout ghcr.io

    - name: Build plugins
      run: |
        pushd plugins
        files=()
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          files+=($(cut -d/ -f2 <<< $file))
        done
        for plugin in $(printf "%s\n" "${files[@]}" | sort -u); do
          pushd $plugin
          docker run --rm -i -v $PWD:/plugin -v /tmp/output/$plugin:/out ghcr.io/steamdeckhomebrew/builder:latest
          echo Built $plugin
          ls -lla /tmp/output/$plugin
          popd
        done
        popd